### ISSUE TITLE
KeyError thrown on import

### ISSUE THREAD

**Issue by Jonbroad15** [sbliven/rcsbsearch#1] opened 2021-03-26 13:16 UTC
Hi,

I was previously using rcsbsearch and it was working fine. However the next time I ran my program a KeyError exception was thrown on import. Not sure why this happens. It was previously working in my python3.9 environment. I tried installing the package on a fresh 3.7 environment and still got the same error:

`import rcsbsearch`

error: 
`
Traceback (most recent call last):
  File "prepare_data/filters.py", line 12, in <module>
    from rcsbsearch import TextQuery, rcsb_attributes
  File "/Users/jonbroad/anaconda3/envs/py37/lib/python3.7/site-packages/rcsbsearch/__init__.py", line 11, in <module>
    from .schema import rcsb_attributes
  File "/Users/jonbroad/anaconda3/envs/py37/lib/python3.7/site-packages/rcsbsearch/schema.py", line 55, in <module>
    rcsb_attributes = _make_schema()
  File "/Users/jonbroad/anaconda3/envs/py37/lib/python3.7/site-packages/rcsbsearch/schema.py", line 52, in _make_schema
    return _make_group("", json)
  File "/Users/jonbroad/anaconda3/envs/py37/lib/python3.7/site-packages/rcsbsearch/schema.py", line 43, in _make_group
    childgroup = _make_group(fullchildname, childnode)
  File "/Users/jonbroad/anaconda3/envs/py37/lib/python3.7/site-packages/rcsbsearch/schema.py", line 38, in _make_group
    return _make_group(fullname, node["items"])
  File "/Users/jonbroad/anaconda3/envs/py37/lib/python3.7/site-packages/rcsbsearch/schema.py", line 43, in _make_group
    childgroup = _make_group(fullchildname, childnode)
  File "/Users/jonbroad/anaconda3/envs/py37/lib/python3.7/site-packages/rcsbsearch/schema.py", line 38, in _make_group
    return _make_group(fullname, node["items"])
  File "/Users/jonbroad/anaconda3/envs/py37/lib/python3.7/site-packages/rcsbsearch/schema.py", line 43, in _make_group
    childgroup = _make_group(fullchildname, childnode)
  File "/Users/jonbroad/anaconda3/envs/py37/lib/python3.7/site-packages/rcsbsearch/schema.py", line 38, in _make_group
    return _make_group(fullname, node["items"])
  File "/Users/jonbroad/anaconda3/envs/py37/lib/python3.7/site-packages/rcsbsearch/schema.py", line 34, in _make_group
    if node["type"] in ("string", "number", "integer", "date"):
KeyError: 'type'
`

**Comment by sbliven** [comment] 2021-04-20 18:45
This was caused by a change in the upstream schema. It was fixed in v0.2.2.

**Closed as completed by sbliven** 2021-04-20 18:45 UTC
